import { describe, expect, it } from 'vitest';
import { IMAGE_REF_SCHEME, type ImageAttachment, type OpenIssue } from '../types.ts';
import {
  PREFILTER_KEEP,
  PREFILTER_THRESHOLD,
  buildSystemPrompt,
  buildUserPrompt,
  prefilterCandidates,
} from './prompt.ts';

const image = (id: string, annotated = false): ImageAttachment => ({
  id,
  bytes: new Uint8Array([1]),
  mediaType: 'image/png',
  annotated,
});

const issue = (number: number, title: string, updatedAt = '2026-07-01T00:00:00Z'): OpenIssue => ({
  number,
  title,
  labels: [],
  updatedAt,
});

const filler = (n: number, from = 1): OpenIssue[] =>
  Array.from({ length: n }, (_, i) => issue(from + i, `Unrelated placeholder ${from + i}`));

describe('buildSystemPrompt', () => {
  const prompt = buildSystemPrompt();

  it('is one stable content source, identical for every provider and call', () => {
    // Claude gets this via --system-prompt, Codex via AGENTS.md. Same string or the
    // ticket format has silently forked.
    expect(buildSystemPrompt()).toBe(prompt);
    expect(prompt.length).toBeGreaterThan(500);
  });

  it('states the no-fabrication rule as a constraint', () => {
    expect(prompt).toMatch(/NEVER INVENT INFORMATION/);
    expect(prompt).toMatch(/OMIT, DO NOT PAD/);
    expect(prompt).toMatch(/never invent repro steps/i);
    expect(prompt).toMatch(/N\/A/);
  });

  it('names every section heading of every report type', () => {
    for (const heading of [
      'Repro steps',
      'Expected',
      'Actual',
      'Environment',
      'Problem',
      'Proposed solution',
      'What',
      'Why',
    ]) {
      expect(prompt).toContain(heading);
    }
    for (const type of ['bug', 'feature', 'chore']) expect(prompt).toContain(type);
  });

  it('pins the title rules: prefix-free, <= 70 chars, symptom vs imperative', () => {
    expect(prompt).toMatch(/NO PREFIX/);
    expect(prompt).toContain('70 characters');
    expect(prompt).toMatch(/SYMPTOM/);
    expect(prompt).toMatch(/IMPERATIVE/);
  });

  it('forces English output regardless of input language', () => {
    expect(prompt).toMatch(/ENGLISH ONLY/);
  });

  it('teaches exactly the image placeholder scheme from types.ts', () => {
    expect(prompt).toContain(`![short description](${IMAGE_REF_SCHEME}<id>)`);
    expect(prompt).toContain(`${IMAGE_REF_SCHEME}img_1`);
    expect(prompt).toMatch(/not a URL/);
  });

  it('forbids any marker, footer, or attribution', () => {
    expect(prompt).toMatch(/NO ATTRIBUTION/);
    expect(prompt).toMatch(/generated by/i);
    expect(prompt).toMatch(/footer/i);
  });

  it('never names the tool, so a prompt echo cannot leak a marker into a ticket', () => {
    // The image scheme is the one legitimate occurrence.
    expect(prompt.replaceAll(IMAGE_REF_SCHEME, '')).not.toMatch(/quacket/i);
  });
});

describe('buildUserPrompt', () => {
  it('carries the raw observation through verbatim, messy and mixed-language', () => {
    const raw = '按 refine 就轉圈圈轉不停 stuck forever, 第二次就好了 weird';
    expect(buildUserPrompt(raw, [], [])).toBe(`<raw_report>\n${raw}\n</raw_report>`);
  });

  it('omits the images block entirely when nothing is attached', () => {
    expect(buildUserPrompt('raw', [], [])).not.toContain('<images>');
  });

  it('lists image ids in attachment order and flags the annotated ones', () => {
    const prompt = buildUserPrompt('raw', [image('img_1'), image('img_2', true)], []);
    expect(prompt).toContain('<images>\nimg_1\nimg_2 (the developer marked this one up)\n</images>');
  });

  it('omits the open-issues block entirely when the repo has none', () => {
    expect(buildUserPrompt('raw', [], [])).not.toContain('<open_issues>');
  });

  it('folds candidates in as one "#<number> <title>" line each', () => {
    const prompt = buildUserPrompt('raw', [], [
      issue(41, 'Repo picker is slow to open'),
      issue(7, 'Login button does nothing'),
    ]);
    expect(prompt).toContain(
      '<open_issues>\n#41 Repo picker is slow to open\n#7 Login button does nothing\n</open_issues>',
    );
  });

  it('sends labels and timestamps nowhere — detection is title-only', () => {
    const prompt = buildUserPrompt('raw', [], [
      { number: 41, title: 'Repo picker is slow', labels: ['bug', 'ui'], updatedAt: '2026-07-01T00:00:00Z' },
    ]);
    expect(prompt).not.toContain('2026-07-01');
    expect(prompt).not.toContain('ui');
  });

  it('leaks no marker of its own', () => {
    expect(buildUserPrompt('raw', [image('img_1')], [issue(1, 'T')])).not.toMatch(/quacket/i);
  });
});

describe('prefilterCandidates', () => {
  it('passes everything through untouched at the threshold', () => {
    const issues = filler(PREFILTER_THRESHOLD);
    expect(prefilterCandidates(issues, 'login button broken')).toEqual(issues);
  });

  it.each([0, 1, 50, PREFILTER_THRESHOLD - 1, PREFILTER_THRESHOLD])(
    'passes all %i issues through in original order',
    (n) => {
      const issues = filler(n);
      const out = prefilterCandidates(issues, 'anything at all');
      expect(out).toHaveLength(n);
      expect(out).toEqual(issues);
    },
  );

  it('engages only past the threshold, trimming to the top N', () => {
    const out = prefilterCandidates(filler(PREFILTER_THRESHOLD + 1), 'login button broken');
    expect(out).toHaveLength(PREFILTER_KEEP);
  });

  it('coarse-ranks by fuzzy title match once engaged', () => {
    const issues = [
      ...filler(150),
      issue(777, 'Login button does nothing on second click', '2020-01-01T00:00:00Z'),
      ...filler(150, 1000),
    ];
    const out = prefilterCandidates(issues, 'login button does nothing when I click it twice');

    expect(out).toHaveLength(PREFILTER_KEEP);
    // The one real match survives despite being the oldest issue in the repo.
    expect(out[0]?.number).toBe(777);
  });

  it('matches Chinese titles, which have no word boundaries to tokenize on', () => {
    const issues = [
      ...filler(250),
      issue(742, '登入按鈕點兩次才有反應', '2020-01-01T00:00:00Z'),
    ];
    const out = prefilterCandidates(issues, '登入按鈕壞掉');
    expect(out[0]?.number).toBe(742);
  });

  it('falls back to most-recently-updated when the text matches nothing', () => {
    const issues = [
      ...filler(250).map((i) => ({ ...i, updatedAt: '2020-01-01T00:00:00Z' })),
      issue(999, 'Completely different placeholder', '2026-07-16T00:00:00Z'),
    ];
    const out = prefilterCandidates(issues, 'zzzz nothing shares a token with this');
    expect(out[0]?.number).toBe(999);
  });

  it('does not let a shared stopword outrank a real match', () => {
    const issues = [
      ...filler(250).map((i) => ({ ...i, title: `The issue with the thing ${i.number}` })),
      issue(777, 'Refine spinner hangs', '2020-01-01T00:00:00Z'),
    ];
    const out = prefilterCandidates(issues, 'the refine spinner hangs with the thing');
    expect(out[0]?.number).toBe(777);
  });
});
